### ISSUE TITLE
解釈が逆の部分がある

### ISSUE THREAD

**Issue by hotteam** [sky-y/site-pandoc-jp#1]
ユーザーズガイド　ソース165行目

>  例えば、LaTeXファイルのhello.txtを入力とし、Markdownに出力する場合は、以下のようなコマンドを実行します：
>```
> pandoc -f markdown -t latex hello.txt
>```

この部分の
英語の本家確認したところ

>  (The input format can be specified using the -f/--from option, the output format using the -t/--to option.) Thus, to convert hello.txt from Markdown to LaTeX, you could type:
>```
> pandoc -f markdown -t latex hello.txt
>```

で間違いがなければ、日本語訳版説明におけるLaTeXとMarkdownの記述が逆です。
正しくは

> 例えば、**Markdown** ファイルのhello.txtを入力とし、**LaTeX** に出力する場合は、以下のようなコマンドを実行します：

この順序になるはず。

**Comment by kishiyamat** [comment]
https://github.com/sky-y/site-pandoc-jp/blob/gh-pages/users-guide/index.html#L165
ですよね。たしかに逆…。フォークしてプルリク送りました。
(あとバージョンも恐らく2以前のモノですし、あまり更新はもうされないのかも気になっていたり)

**Comment by sky-y** [comment]
@hotteam @kisiyama ご報告ありがとうございます。
返信が大変遅くなり、ご心配をおかけしました。申し訳ありません。

現在、ユーザーズガイド日本語版の改訂作業を進めています。
今はひとまず、翻訳のための基盤を整備した段階です。

GitHub: pandoc-jp/pandoc-doc-ja
https://github.com/pandoc-jp/pandoc-doc-ja

（新装工事中）Pandocユーザーズガイド日本語版 トップ
https://pandoc-doc-ja.readthedocs.io/ja/latest/

そのため、本Issueに関しては、pandoc-jp/pandoc-doc-ja のIssueに転記した上でcloseします。

[旧Issue：解釈が逆の部分がある · Issue #1 · pandoc-jp/pandoc-doc-ja](https://github.com/pandoc-jp/pandoc-doc-ja/issues/1)

> (あとバージョンも恐らく2以前のモノですし、あまり更新はもうされないのかも気になっていたり)

今回の改訂で、現在のバージョン（Pandoc 2.5）に追いつこうとしています。
またCI（Read the Docs）の導入など、本家への追従がしやすい体制にしていく方針です。

引き続き、よろしくお願いいたします。
